### ISSUE TITLE
definder 报毒

### ISSUE THREAD

**Issue by mgy-qyqf** [gc-toolkit/OceanLauncher#3]
如图
![4WRU34P%A(M 7A0~(`0}0 5](https://user-images.githubusercontent.com/73788063/179398944-003cae3a-44b3-487f-ac24-a550539e07ca.png)
版本是v1.3.2-dev
执行勾选启用代理并安装证书后发生的
![image](https://user-images.githubusercontent.com/73788063/179399081-ba2ede03-1702-46b3-aaf7-7487927a3aa5.png)

**Comment by SwetyCore** [comment]
源码是完全公开的，如果不信任可自行编译(
