### ISSUE TITLE
一点击启动代理就崩溃

### ISSUE THREAD

**Issue by ImagineDeerTech** [gc-toolkit/OceanLauncher#6]
如图，尝试管理员启动也不行，检查端口也无占用，帮帮忙。
![Ocean Launcher 2022_8_19 0_36_31](https://user-images.githubusercontent.com/78028529/185450257-c0850039-78d6-4d4f-8603-fb5e53b6c35c.png)

**Comment by kaixin1995** [comment]
我也是这样，拉下来代码检查了一下，他写的有点大意了。  在赋值后重新初始化了，导致他的配置文件全部未生效。改下，放在if里面就可以了。
![image](https://user-images.githubusercontent.com/45955796/185726587-084ca967-a95a-468c-84f4-ce8db6767305.png)

**Comment by kaixin1995** [comment]
或者给你另外一个解决办法，查看本地谁占用了1145端口，干掉这个程序就可以了。  希望可以快点修复这个问题。

**Comment by SwetyCore** [comment]
此启动器已废弃，请转到新项目：https://github.com/gc-toolkit/GenshinLauncher
